# Generated by Django 4.0.2 on 2022-02-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
