# Generated by Django 4.0.2 on 2022-02-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clients_date_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contrats',
        ),
    ]
